name: Build luci-theme-argon .run package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout RunFileBuilder repo
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "PKG_NAME=luci-theme-argon" >> $GITHUB_ENV
          echo "TAG=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV
          echo "TARGET=all" >> $GITHUB_ENV
          echo "RUN_FILE=luci-theme-argon_$(date +%Y%m%d-%H%M)_all.run" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip git zstd build-essential

      - name: Download luci-theme-argon .ipk
        run: |
          mkdir -p appdir
          cd appdir
          curl -LO https://github.com/jerrykuku/luci-theme-argon/releases/download/v2.3.2/luci-theme-argon_2.3.2-r20250207_all.ipk

      - name: Add install.sh script
        run: |
          cat <<EOF > appdir/install.sh
          #!/bin/sh
          opkg update
          if [ \$? -ne 0 ]; then
              echo "opkg update failed."
              exit 1
          fi
          opkg install luci-theme-argon_2.3.2-r20250207_all.ipk
          EOF
          chmod +x appdir/install.sh

      - name: Clone makeself
        run: git clone https://github.com/megastep/makeself.git

      - name: Create .run package
        run: |
          chmod +x makeself/makeself.sh
          makeself/makeself.sh appdir ${{ env.RUN_FILE }} "Install luci-theme-argon" ./install.sh

      - name: Check result
        run: ls -lh *.run

      - name: Push .run to Immortalwrt-ImageBuilder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/waynesg/Immortalwrt-ImageBuilder.git target-repo
          find target-repo/extra-packages/ -type f -name "luci-theme-argon_*.run" ! -name "${{ env.RUN_FILE }}" -delete
          cp ${{ env.RUN_FILE }} target-repo/extra-packages/
          cd target-repo
          git add extra-packages/${{ env.RUN_FILE }}
          git commit -m "🤖 同步 luci-theme-argon: ${{ env.RUN_FILE }}"
          git push
