name: Build luci-theme-argon .run package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout RunFileBuilder repo
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "PKG_NAME=luci-theme-argon" >> $GITHUB_ENV
          echo "TARGET=all" >> $GITHUB_ENV

      - name: Get latest release tag
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/jerrykuku/luci-theme-argon/releases/latest | jq -r '.tag_name')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RUN_FILE=luci-theme-argon_${VERSION}_all.run" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip git zstd build-essential

      - name: Download luci-theme-argon .ipk
        run: |
          mkdir -p appdir
          cd appdir

          API="https://api.github.com/repos/jerrykuku/luci-theme-argon/releases/latest"
          URL=$(curl -s $API | jq -r '.assets[] | select(.name | test("luci-theme-argon_.*\\.ipk")) | .browser_download_url')
          echo "Download URL: $URL"
          curl -LO "$URL"

      - name: Add install.sh script
        run: |
          cd appdir
          IPK_FILE=$(ls luci-theme-argon_*.ipk)
          cat <<EOF > install.sh
          #!/bin/sh
          opkg update
          if [ \$? -ne 0 ]; then
              echo "opkg update failed."
              exit 1
          fi
          opkg install \$IPK_FILE
          EOF
          chmod +x install.sh

      - name: Clone makeself
        run: git clone https://github.com/megastep/makeself.git

      - name: Create .run package
        run: |
          chmod +x makeself/makeself.sh
          makeself/makeself.sh appdir "${{ env.RUN_FILE }}" "Install luci-theme-argon" ./install.sh

      - name: Check result
        run: ls -lh *.run

      - name: Push .run to Immortalwrt-ImageBuilder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/waynesg/Immortalwrt-ImageBuilder.git target-repo

          cd target-repo
          git checkout main

          # 删除旧的 luci-theme-argon_*.run（除当前外）
          find extra-packages/ -type f -name "luci-theme-argon_*.run" ! -name "${{ env.RUN_FILE }}" -delete

          # 拷贝新 .run 文件
          cp ../${{ env.RUN_FILE }} extra-packages/

          git add extra-packages/${{ env.RUN_FILE }}
          git commit -m "🤖 同步 luci-theme-argon: ${{ env.RUN_FILE }}"
          git push
