#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

name: NEW Make Passwall2 run files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fetch latest release tag from Passwall2
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall2/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Set .run filename
        run: |
          DATE=$(date +%Y%m%d)
          echo "RUN_FILE=luci-app-passwall2_x86_64_${DATE}.run" >> $GITHUB_ENV

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest Passwall files
        run: |
          mkdir -p downloads
          cd downloads
          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall2/releases/latest | grep -oP '"browser_download_url":\s*".*passwall_packages_ipk_x86_64.zip"' | cut -d '"' -f 4)
          #curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall2/releases/latest | grep -oP '"browser_download_url":\s*".*passwall_packages_ipk_aarch64_cortex-a53.zip"' | cut -d '"' -f 4)
          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall2/releases/latest | grep -oP '"browser_download_url":\s*".*luci-24.10.*\.ipk"' | head -1 | cut -d '"' -f 4)
          curl -LO $(curl -s https://api.github.com/repos/xiaorouji/openwrt-passwall2/releases/latest | grep -oP '"browser_download_url":\s*".*luci-24.10.*\.ipk"' | tail -1 | cut -d '"' -f 4)
      
      - name: Organize files for x86_64
        run: |
          mkdir -p passwall_x86_64/depends passwall_x86_64/main
          unzip downloads/passwall_packages_ipk_x86_64.zip -d passwall_x86_64/depends
          rm downloads/passwall_packages_ipk_x86_64.zip
          cp downloads/luci-24.10*.ipk passwall_x86_64/main/

      # - name: Organize files for aarch64_cortex-a53
      #   run: |
      #     mkdir -p passwall_aarch64/depends passwall_aarch64/main
      #     unzip downloads/passwall_packages_ipk_aarch64_cortex-a53.zip -d passwall_aarch64/depends
      #     rm downloads/passwall_packages_ipk_aarch64_cortex-a53.zip
      #     cp downloads/luci-24.10*.ipk passwall_aarch64/main/

      - name: Create install.sh scripts
        run: |
          cat <<EOF > passwall_x86_64/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install iptables-mod-tproxy
          opkg install iptables-mod-socket
          opkg install iptables-mod-iprange
          opkg install iptables-mod-conntrack-extra
          opkg install depends/*.ipk
          opkg install main/*.ipk
          EOF
          chmod +x passwall_x86_64/install.sh
          # cp passwall_x86_64/install.sh passwall_aarch64/install.sh

      - name: Move passwall2 directories to makeself
        run: |
          mv passwall_x86_64 makeself/
          # mv passwall_aarch64 makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
            ./makeself.sh passwall_x86_64/ ${{ env.RUN_FILE }} "by github action" ./install.sh
            # ./makeself.sh passwall_aarch64/ passwall2_aarch64_a53_${{ env.LATEST_TAG }}.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/passwall2*.run

      - name: Preparing release name
        run: |
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV


      - name: Push run file to Immortalwrt-ImageBuilder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/waynesg/Immortalwrt-ImageBuilder.git target-repo

          find target-repo/extra-packages/ -type f -name "luci-app-passwall2_*.run" ! -name "${{ env.RUN_FILE }}" -delete
          # 复制当前构建的 .run 文件
          cp makeself/${{ env.RUN_FILE }} target-repo/extra-packages/

          cd target-repo
          git checkout main

          git add extra-packages/${{ env.RUN_FILE }}
          git commit -m "🤖 自动同步 Passwall RunFile: $(date +%F_%T)"
          git push
